excluded:
  - Package.swift

included:
  - Sources
  - Tests

disabled_rules:
  - block_based_kvo
  - class_delegate_protocol
  - colon
  - cyclomatic_complexity
  - force_cast
  - force_try
  - force_unwrapping
  - function_body_length
  - function_parameter_count
  - identifier_name
  - nesting
  - notification_center_detachment
  - no_fallthrough_only
  - no_space_in_method_call
  - redundant_string_enum_value
  - todo
  - trailing_comma
  - type_body_length
  - opening_brace
  - untyped_error_in_catch

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - convenience_type
  - empty_string
  - empty_xctest_method
  - explicit_enum_raw_value
  - explicit_init
  - first_where
  - generic_type_name
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - last_where
  - legacy_multiple
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - no_extension_access_modifier
  - override_in_extension
  - pattern_matching_keywords
  - redundant_nil_coalescing
  - sorted_first_last
  - sorted_imports
  - switch_case_on_newline
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - yoda_condition

implicit_return:
  included: 
    - closure

file_length:
  warning: 400
  error: 1000
  ignore_comment_only_lines: true

line_length:
  warning: 135
  error: 140
  ignores_urls: true
  ignores_comments: true
  ignores_function_declarations: true

generic_type_name:
  min_length: 2

attributes:
  always_on_line_above:
    - "@usableFromInline"
    - "@inlinable"