name: Deploy DocC Documentation

on:
  push:
    branches: [ "develop" ]

permissions:
  contents: write

jobs:
  docs:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Swift version
        run: swift --version

      - name: Build package
        run: swift build

      - name: Build documentation
        run: |
          swift package \
            --allow-writing-to-directory ./docs \
            generate-documentation \
            --target OpenSwiftUI \
            --output-path ./docs \
            --transform-for-static-hosting \
            --hosting-base-path OpenSwiftUI

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: docs
          force_orphan: true