name: MacOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Test:
    name: Execute tests on MacOS
    strategy:
      matrix:
        include:
          - os: macos-latest
            xcode-version: "13.3.1"
    runs-on: ${ { matrix.os } }
    steps:
    - uses: actions/checkout@v3
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${ { matrix.xcode-version } }
    - name: Swift Version
      run: swift --version
    - name: Build and run tests in debug mode with coverage
      run: |
        swift test \
          -c debug \
          -Xswiftc -warnings-as-errors \
          --enable-code-coverage \
          --build-path .build-test-debug