name: MacOS

on:
  pull_request:
    branches: [ develop ]

jobs:
  Test:
    name: Execute tests on MacOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Swift Version
      run: swift --version
    - name: Build and run tests in debug mode with coverage
      run: |
        swift test \
          -c debug \
          --enable-code-coverage \
          --build-path .build-test-debug
