name: MacOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Test:
    name: Unit Test
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-11
            xcode-version: "12.5.1" # Swift 5.4.2
          - os: macos-latest
            xcode-version: "13.3.1" # Swift 5.5.2
    runs-on: ${ { matrix.os } }
    steps:
    - uses: actions/checkout@v3
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${ { matrix.xcode-version } }
    - name: Swift Version
      run: swift --version
    - name: Build and run tests in debug mode with coverage
      run: |
        swift test \
          -c debug \
          -Xswiftc -warnings-as-errors \
          --enable-code-coverage \
          --build-path .build-test-debug
        xcrun llvm-cov show \
          -instr-profile=.build-test-debug/debug/codecov/default.profdata \
          .build-test-debug/debug/OpenSwiftUITests.xctest/Contents/MacOS/OpenSwiftTests \
          > coverage.txt