name: MacOS

on:
  push:
    branches: [ tests/macos ]
  pull_request:
    branches: [ main ]

jobs:
  Test:
    name: Execute tests on MacOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Swift Version
      run: swift --version
    - name: Build and run tests in debug mode with coverage
      run: |
        swift test \
          -c debug \
          -Xswiftc -warnings-as-errors \
          --enable-code-coverage \
          --build-path .build-test-debug