name: SwiftLint

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/SwiftLint.yml"
      - ".swiftlint.yml"
      - "**/*.swift"
  pull_request:
    paths:
      - ".github/workflows/SwiftLint.yml"
      - ".swiftlint.yml"
      - "**/*.swift"

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Action for SwiftLint
        uses: mayk-it/action-swiftlint@3.2.2