
name: Swift on Ubuntu

on:
  push:
    branches:
      - develop

jobs:
  build-test:
    runs-on: ubuntu-latest # Or ubuntu-22.04, etc.
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Swift
        uses: swift-actions/setup-swift@v3 # Or your preferred action
        with:
          swift-version: '6.2' # Specify your desired Swift version

      - name: Build project
        run: swift build

      - name: Run tests
        run: swift test
