
name: Swift on Ubuntu

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Swift
        uses: swift-actions/setup-swift@v3
        with:
          skip-verify-signature: true
          swift-version: '6.2'
      - name: Getting Swift Version
        run: swift --version

      - name: Build project
        run: swift build