name: Ubuntu 

on:
  pull_request:
    branches: [ develop ]

jobs:
  ubuntu_test:
    name: Execute tests on Ubuntu
    strategy:
      fail-fast: false
      matrix:
        swift_version: ["6.0"]
    runs-on: ubuntu-latest
    container: swift:${{ matrix.swift_version }}-bionic
    steps:
      - uses: actions/checkout@v4
      - name: Building and running tests in debug mode with coverage
        run: |
          swift test \
            -c debug \
            --enable-code-coverage \
            --build-path .build-test-debug