name: Windows 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Test:
    name: Execute tests on Windows
    strategy:
      fail-fast: false
      matrix:
        swift_version: ["5.5.0", "5.5.1"]
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: MaxDesiatov/swift-windows-action@v1
        with:
          swift-version: ${{ matrix.swift_version }}