name: Windows 

on:
  push:
    branches: 
      - develop

jobs:
  Test:
    name: Execute tests on Windows
    runs-on: windows-latest
    steps:
      # - uses: compnerd/gha-setup-swift@main
      - uses: actions/checkout@v4
      - run: swift build