name: Windows 

on:
  push:
    branches: 
      - develop

jobs:
  Test:
    name: Execute tests on Windows
    strategy:
      fail-fast: false
      matrix:
        swift_version: ["6.0"]
    runs-on: windows-latest
    steps:
      - uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-6.0-release
          tag: 6.0-RELEASE

      - uses: actions/checkout@v4
      - run: swift build


