name: Windows 

on:
  push:
    branches: 
      - develop

jobs:
  Test:
    name: Execute tests on Windows
    runs-on: windows-latest
    steps:
      - uses: compnerd/gha-setup-swift@main
        with:
            swift-version: swift-6.2-release
            swift-build: 6.2-RELEASE
      - uses: actions/checkout@v4
      - run: swift build